CREATE GENERATOR GER_CLIENTES;
CREATE GENERATOR GER_COMPRAS;
CREATE GENERATOR GER_CORRECOES;
CREATE GENERATOR GER_FORNECEDORES;
CREATE GENERATOR GER_ITENS_COMPRA;
CREATE GENERATOR GER_ITENS_PEDIDO;
CREATE GENERATOR GER_PEDIDOS;
CREATE GENERATOR GER_PRODUTOS;

CREATE TABLE CLIENTES
(
  ID_CLIENTE integer NOT NULL,
  NOME varchar(40) COLLATE UNICODE_CI_AI,
  NASCIMENTO date,
  CPF varchar(14) COLLATE UNICODE_CI_AI,
  RG varchar(20) COLLATE UNICODE_CI_AI,
  TELEFONE varchar(14) COLLATE UNICODE_CI_AI,
  CELULAR varchar(14) COLLATE UNICODE_CI_AI,
  ENDERECO varchar(50) COLLATE UNICODE_CI_AI,
  BAIRRO varchar(30) COLLATE UNICODE_CI_AI,
  CIDADE varchar(30) COLLATE UNICODE_CI_AI,
  CEP varchar(9) COLLATE UNICODE_CI_AI,
  ESTADO varchar(2) COLLATE UNICODE_CI_AI,
  EMAIL varchar(80) COLLATE UNICODE_CI_AI,
  ENDERECO_COMERCIAL varchar(50) COLLATE UNICODE_CI_AI,
  CNPJ varchar(20) COLLATE UNICODE_CI_AI,
  REFERENCIAS blob sub_type 1,
  CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE)
);
CREATE TABLE COMPRAS
(
  ID_COMPRA integer NOT NULL,
  ID_FORNECEDOR integer NOT NULL,
  DATA date,
  NOTA varchar(10) COLLATE UNICODE_CI_AI,
  TOTAL decimal(10,2),
  CONSTRAINT PK_COMPRAS PRIMARY KEY (ID_COMPRA)
);
CREATE TABLE FORNECEDORES
(
  ID_FORNECEDOR integer NOT NULL,
  NOME varchar(40) COLLATE UNICODE_CI_AI,
  TELEFONE_1 varchar(14) COLLATE UNICODE_CI_AI,
  TELEFONE_2 varchar(14) COLLATE UNICODE_CI_AI,
  ENDERECO varchar(50) COLLATE UNICODE_CI_AI,
  BAIRRO varchar(30) COLLATE UNICODE_CI_AI,
  CIDADE varchar(30) COLLATE UNICODE_CI_AI,
  CEP varchar(9) COLLATE UNICODE_CI_AI,
  ESTADO varchar(2) COLLATE UNICODE_CI_AI,
  EMAIL varchar(80) COLLATE UNICODE_CI_AI,
  CNPJ varchar(20) COLLATE UNICODE_CI_AI,
  INSCRICAO_ESTADUAL varchar(20) COLLATE UNICODE_CI_AI,
  CONSTRAINT PK_FORNECEDORES PRIMARY KEY (ID_FORNECEDOR)
);
CREATE TABLE ITENS_COMPRA
(
  ID_ITEM integer NOT NULL,
  ID_COMPRA integer NOT NULL,
  ID_PRODUTO integer NOT NULL,
  PRECO_UNITARIO decimal(10,2) NOT NULL,
  QUANTIDADE integer NOT NULL,
  CONSTRAINT PK_ITENS_COMPRA PRIMARY KEY (ID_ITEM)
);
CREATE TABLE ITENS_PEDIDO
(
  ID_ITEM integer NOT NULL,
  ID_PEDIDO integer NOT NULL,
  ID_PRODUTO integer NOT NULL,
  PRECO_UNITARIO decimal(10,2) NOT NULL,
  QUANTIDADE integer NOT NULL,
  CONSTRAINT PK_ITENS_PEDIDO PRIMARY KEY (ID_ITEM)
);
CREATE TABLE PEDIDOS
(
  ID_PEDIDO integer NOT NULL,
  ID_CLIENTE integer NOT NULL,
  DATA date NOT NULL,
  TOTAL decimal(10,2) NOT NULL,
  CONSTRAINT PK_PEDIDOS PRIMARY KEY (ID_PEDIDO)
);
CREATE TABLE PRODUTOS
(
  ID_PRODUTO integer NOT NULL,
  ID_FORNECEDOR integer,
  CODIGO varchar(10) COLLATE UNICODE_CI_AI,
  NOME varchar(80) COLLATE UNICODE_CI_AI,
  QUANTIDADE integer,
  PRECO_CUSTO_UNIT decimal(10,2),
  CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID_PRODUTO)
);

CREATE INDEX CLIENTES_PESQUISA ON CLIENTES (NOME);
ALTER TABLE COMPRAS ADD CONSTRAINT FK_COMPRAS_FORNECEDORES
  FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES (ID_FORNECEDOR);
CREATE INDEX FORNECEDORES_PESQUISA ON FORNECEDORES (NOME);
ALTER TABLE ITENS_COMPRA ADD CONSTRAINT FK_ITENS_COMPRAS
  FOREIGN KEY (ID_COMPRA) REFERENCES COMPRAS (ID_COMPRA) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ITENS_COMPRA ADD CONSTRAINT FK_ITENS_COMPRA_PRODUTOS
  FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID_PRODUTO);
ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT FK_ITENS_PEDIDO_PEDIDOS
  FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT FK_ITENS_PEDIDO_PRODUTOS
  FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID_PRODUTO);
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_CLIENTES
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE);
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_FORNECEDORES
  FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES (ID_FORNECEDOR);
CREATE INDEX PRODUTOS_CODIGO ON PRODUTOS (CODIGO);